export const siteConfig = {
  name: 'A&M FutureTech Solution Pvt Ltd',
  email: 'info@amfuturetech.com',
  phone: '+91 00000 00000',
  address: 'India',
  socials: {
    linkedin: '#',
    facebook: '#',
    instagram: '#',
    x: '#',
    youtube: '#',
  },
  navItems: [
    { label: 'Home', href: '/' },
    { label: 'About Us', href: '/about' },
    { label: 'Services', href: '/services' },
    { label: 'Solutions', href: '/solutions' },
    { label: 'Portfolio', href: '/portfolio' },
    { label: 'Technologies', href: '/technologies' },
    { label: 'Industries', href: '/industries' },
    { label: 'Careers', href: '/careers' },
    { label: 'Contact Us', href: '/contact' },
  ],
  stats: [
    { label: 'Projects Completed', value: '150+', suffix: '+' },
    { label: 'Happy Clients', value: '90', suffix: '%' },
    { label: 'Technologies Used', value: '25', suffix: '+' },
    { label: 'Support & Innovation', value: '24/7', suffix: '' },
  ],
  serviceCards: [
    {
      title: 'Custom Software Development',
      description: 'Scalable enterprise software built around your business workflows, security needs, and growth goals.',
      features: ['ERP Systems', 'CRM Systems', 'HRMS & Payroll', 'Accounting Software', 'Inventory Management', 'Warehouse Management Systems', 'Business Management Software', 'Custom Enterprise Applications'],
    },
    {
      title: 'Website Development',
      description: 'High-converting business and marketing websites tailored for trust, speed, and long-term digital growth.',
      features: ['Corporate Websites', 'Business Websites', 'E-Commerce Websites', 'Portfolio Websites', 'Custom Web Applications', 'Admin Panels', 'Progressive Web Applications'],
    },
    {
      title: 'Mobile Application Development',
      description: 'User-friendly mobile apps built for performance, reliability, and measurable business impact.',
      features: ['Android Applications', 'iOS Applications', 'Cross-Platform Applications', 'Business Applications', 'E-Commerce Apps', 'On-Demand Applications'],
    },
    {
      title: 'Web Application Development',
      description: 'Robust platform solutions that streamline operations, data access, and digital experiences across teams.',
      features: ['SaaS Platforms', 'Business Portals', 'Enterprise Applications', 'Custom Dashboards', 'Cloud-Based Applications'],
    },
    {
      title: 'UI/UX Design',
      description: 'Modern, intuitive user experiences that improve engagement, trust, and conversion across digital products.',
      features: ['Website UI/UX', 'Mobile App Design', 'Dashboard Design', 'Wireframes', 'Prototypes', 'User Experience Optimization'],
    },
    {
      title: 'Cloud Solutions',
      description: 'Cloud-native architecture and deployment services that improve agility, uptime, and scale.',
      features: ['Cloud Application Development', 'Cloud Migration', 'Deployment', 'Cloud Infrastructure', 'Backup & Storage Solutions'],
    },
    {
      title: 'API & Third-Party Integration',
      description: 'Secure and reliable integrations connecting your systems, platforms, and payment workflows.',
      features: ['Payment Gateway Integration', 'Banking API Integration', 'ERP Integrations', 'CRM Integrations', 'REST APIs', 'Secure Third-Party Integrations'],
    },
    {
      title: 'E-Commerce Solutions',
      description: 'End-to-end commerce platforms that improve operations, customer experience, and revenue growth.',
      features: ['Complete E-Commerce Platforms', 'Product Management', 'Payment Integration', 'Order Management', 'Customer Portals', 'Mobile Shopping Applications'],
    },
    {
      title: 'IT Consulting',
      description: 'Strategic digital advisory services helping businesses optimize systems and future-proof their growth.',
      features: ['Digital Transformation', 'Software Architecture', 'Technology Consulting', 'Business Process Automation', 'System Planning'],
    },
    {
      title: 'Maintenance & Support',
      description: 'Reliable post-launch support to keep your systems secure, efficient, and continuously improving.',
      features: ['Website Maintenance', 'Application Support', 'Bug Fixing', 'Performance Optimization', 'Security Updates', 'System Enhancements'],
    },
  ],
  solutions: [
    {
      name: 'ERP Solutions',
      overview: 'Unified operational workflows for finance, procurement, inventory, production, and reporting.',
      features: ['Process automation', 'Role-based dashboards', 'Data insights', 'Multi-module integration'],
      benefits: ['Improved efficiency', 'Reduced manual work', 'Better visibility', 'Scalable operations'],
      industries: ['Manufacturing', 'Retail', 'Logistics', 'SMBs'],
    },
    {
      name: 'HRMS & Payroll',
      overview: 'Smart HR systems to manage employees, attendance, payroll, onboarding, and policy workflows.',
      features: ['Attendance tracking', 'Payroll automation', 'Leave management', 'Compliance tools'],
      benefits: ['Faster payroll', 'Accurate records', 'Better employee experience', 'Time savings'],
      industries: ['Corporate', 'Healthcare', 'Education', 'Services'],
    },
    {
      name: 'Accounting & Finance Systems',
      overview: 'Secure financial systems for budgeting, reporting, reconciliation, and operational oversight.',
      features: ['Financial dashboards', 'Invoice automation', 'Expense tracking', 'Cash flow planning'],
      benefits: ['Fewer errors', 'Faster reporting', 'Greater control', 'Reliable compliance'],
      industries: ['Finance', 'Professional services', 'SMBs', 'Real estate'],
    },
    {
      name: 'Inventory Management',
      overview: 'Real-time stock control for procurement, warehousing, order management, and replenishment.',
      features: ['SKU tracking', 'Stock alerts', 'Warehouse logs', 'Vendor management'],
      benefits: ['Reduced stockouts', 'Lower wastage', 'Better planning', 'Higher visibility'],
      industries: ['Retail', 'Logistics', 'Manufacturing', 'Distribution'],
    },
    {
      name: 'Warehouse Management System',
      overview: 'Optimized warehouse operations across receiving, slotting, dispatch, and inventory monitoring.',
      features: ['Picking workflows', 'Bin management', 'Inventory scanning', 'Dispatch tracking'],
      benefits: ['Faster fulfillment', 'Lower errors', 'Higher productivity', 'Inventory accuracy'],
      industries: ['Logistics', 'Retail', 'Manufacturing', 'E-commerce'],
    },
    {
      name: 'CRM Solutions',
      overview: 'Data-driven CRM platforms that align sales, support, and customer lifecycle management.',
      features: ['Lead tracking', 'Customer history', 'Sales pipeline', 'Campaign reporting'],
      benefits: ['Better conversion', 'Improved retention', 'Stronger service', 'Smarter decisions'],
      industries: ['Sales-driven businesses', 'Services', 'Real estate', 'Hospitality'],
    },
    {
      name: 'Project Management',
      overview: 'Operational planning systems for milestones, resources, budgeting, and cross-team visibility.',
      features: ['Task boards', 'Team planning', 'Timeline reporting', 'Resource tracking'],
      benefits: ['Improved execution', 'Clear accountability', 'Faster decisions', 'On-time delivery'],
      industries: ['Consulting', 'Construction', 'IT', 'Professional services'],
    },
    {
      name: 'E-Commerce Solutions',
      overview: 'Modern commerce platforms designed for conversion, order automation, and customer retention.',
      features: ['Product catalogs', 'Secure checkout', 'Order tracking', 'Marketing integrations'],
      benefits: ['Higher sales', 'Better UX', 'Lower friction', 'Operational efficiency'],
      industries: ['Retail', 'Fashion', 'Electronics', 'B2B commerce'],
    },
    {
      name: 'Property Management',
      overview: 'Scalable systems for lease management, maintenance, vendors, and property analytics.',
      features: ['Tenant management', 'Service requests', 'Lease tracking', 'Financial reporting'],
      benefits: ['Better occupancy', 'Lower admin burden', 'Smarter operations', 'Faster issue resolution'],
      industries: ['Real estate', 'Property firms', 'Commercial management', 'Housing'],
    },
    {
      name: 'Asset Management',
      overview: 'Tools for capital asset tracking, lifecycle planning, valuation, and utilization analysis.',
      features: ['Asset register', 'Maintenance logs', 'Depreciation tracking', 'Status monitoring'],
      benefits: ['Better oversight', 'Lower risk', 'Improved planning', 'Greater accountability'],
      industries: ['Manufacturing', 'Construction', 'Healthcare', 'Infrastructure'],
    },
    {
      name: 'Custom Business Portals',
      overview: 'Secure, role-based portals that connect data, teams, customers, and business intelligence.',
      features: ['User roles', 'Workflow automation', 'Document management', 'Custom dashboards'],
      benefits: ['Centralized systems', 'Improved productivity', 'Lower complexity', 'Modern access experience'],
      industries: ['Enterprise', 'Finance', 'Logistics', 'Public sector'],
    },
  ],
  technologies: {
    frontend: ['React', 'Next.js', 'Angular', 'HTML5', 'CSS3', 'JavaScript', 'TypeScript'],
    backend: ['Java', 'Spring Boot', 'Node.js', 'REST APIs'],
    mobile: ['Android', 'iOS', 'Flutter', 'React Native'],
    database: ['MySQL', 'PostgreSQL', 'MongoDB'],
    cloud: ['AWS', 'Azure', 'Docker', 'CI/CD', 'Cloud Deployment'],
  },
  industries: ['Construction', 'Interior & Contracting', 'Logistics', 'Retail', 'E-Commerce', 'Real Estate', 'Healthcare', 'Education', 'Finance', 'Hospitality', 'Manufacturing', 'Small & Medium Businesses'],
  portfolio: [
    {
      category: 'Software Development',
      title: 'Enterprise ERP Suite',
      description: 'Integrated ERP transformation for a fast-growing manufacturing business.',
      technologies: ['Java', 'React', 'MySQL'],
    },
    {
      category: 'Web Development',
      title: 'Digital Brand Platform',
      description: 'High-performing marketing website with modern conversion flows for a service startup.',
      technologies: ['Next.js', 'Tailwind', 'CMS'],
    },
    {
      category: 'Mobile Applications',
      title: 'Smart Service App',
      description: 'Customer and technician app improving scheduling, service requests, and communication.',
      technologies: ['Flutter', 'Node.js', 'MongoDB'],
    },
    {
      category: 'ERP Solutions',
      title: 'Inventory & Fleet Control',
      description: 'A unified platform for tracking warehouse operations, assets, and dispatch workflows.',
      technologies: ['Spring Boot', 'PostgreSQL', 'React'],
    },
    {
      category: 'E-Commerce',
      title: 'Retail Commerce Platform',
      description: 'Multi-category storefront and order management system integrating shipping and payments.',
      technologies: ['Next.js', 'Stripe', 'MySQL'],
    },
  ],
  testimonials: [
    {
      name: 'Aisha Rahman',
      company: 'Nexa Retail',
      role: 'Operations Director',
      review: 'A&M FutureTech transformed our customer journey and operational workflows with a solution that feels premium and performs at scale.',
    },
    {
      name: 'Rahul Verma',
      company: 'BuildCore Infra',
      role: 'Project Lead',
      review: 'Their technical depth and project ownership stood out from day one. The platform they delivered was both reliable and exactly aligned with our goals.',
    },
    {
      name: 'Meera Shah',
      company: 'WellPath Care',
      role: 'Founder',
      review: 'We needed a secure, scalable platform for patient services and internal processes. The team executed with professionalism and precision.',
    },
  ],
  careers: [
    {
      title: 'Senior Full Stack Developer',
      department: 'Engineering',
      type: 'Full Time',
      experience: '4+ Years',
      location: 'Remote / India',
      description: 'Design and build scalable digital products that support modern business operations across web and cloud platforms.',
      requirements: ['Strong experience with React, Next.js, Node.js and REST APIs', 'Solid understanding of architecture, testing, and deployment workflows', 'Excellent communication and collaboration skills'],
    },
    {
      title: 'UI/UX Designer',
      department: 'Design',
      type: 'Full Time',
      experience: '2+ Years',
      location: 'Bengaluru',
      description: 'Create elegant, conversion-focused experiences for businesses looking to modernize their digital presence.',
      requirements: ['Portfolio with responsive design examples', 'Expertise in Figma and design systems', 'Ability to validate usability and refine experiences'],
    },
    {
      title: 'Cloud Engineer',
      department: 'Infrastructure',
      type: 'Full Time',
      experience: '3+ Years',
      location: 'Remote / India',
      description: 'Support cloud deployment, infrastructure automation, and delivery stability for business-critical applications.',
      requirements: ['Hands-on with AWS/Azure and Docker', 'Experience in CI/CD and deployment pipelines', 'Strong scripting and troubleshooting ability'],
    },
  ],
};
